In [1]:
import pandas as pd


In [2]:
df = pd.read_csv('train.csv')

In [3]:
df.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [4]:
df.shape

(20800, 5)

In [5]:
df.isnull().sum()

id           0
title      558
author    1957
text        39
label        0
dtype: int64

In [6]:
df = df.dropna()

In [7]:
X = df.drop('label', axis=1)
y = df['label']

In [8]:
X

id                                              title  \
0          0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1          1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2          2                  Why the Truth Might Get You Fired   
3          3  15 Civilians Killed In Single US Airstrike Hav...   
4          4  Iranian woman jailed for fictional unpublished...   
...      ...                                                ...   
20795  20795  Rapper T.I.: Trump a ’Poster Child For White S...   
20796  20796  N.F.L. Playoffs: Schedule, Matchups and Odds -...   
20797  20797  Macy’s Is Said to Receive Takeover Approach by...   
20798  20798  NATO, Russia To Hold Parallel Exercises In Bal...   
20799  20799                          What Keeps the F-35 Alive   

                                          author  \
0                                  Darrell Lucus   
1                                Daniel J. Flynn   
2                             Consortiumnews.com   
3                                Jessica Purkiss   
4                                 Howard Portnoy   
...                                          ...   
20795                              Jerome Hudson   
20796                           Benjamin Hoffman   
20797  Michael J. de la Merced and Rachel Abrams   
20798                                Alex Ansary   
20799                              David Swanson   

                                                    text  
0      House Dem Aide: We Didn’t Even See Comey’s Let...  
1      Ever get the feeling your life circles the rou...  
2      Why the Truth Might Get You Fired October 29, ...  
3      Videos 15 Civilians Killed In Single US Airstr...  
4      Print \nAn Iranian woman has been sentenced to...  
...                                                  ...  
20795  Rapper T. I. unloaded on black celebrities who...  
20796  When the Green Bay Packers lost to the Washing...  
20797  The Macy’s of today grew from the union of sev...  
20798  NATO, Russia To Hold Parallel Exercises In Bal...  
20799    David Swanson is an author, activist, journa...  

[18285 rows x 4 columns]

In [9]:
X.shape

(18285, 4)

In [10]:
y.shape

(18285,)

In [1]:
import tensorflow as tf

In [ ]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [270]:
voc_size = 10000

In [271]:
content = X.copy()

In [272]:
content['title'][0]

'House Dem Aide: We Didn’t Even See Comey’s Letter Until Jason Chaffetz Tweeted It'

In [273]:
content.reset_index(inplace=True)

In [274]:
content

index     id                                              title  \
0          0      0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1          1      1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2          2      2                  Why the Truth Might Get You Fired   
3          3      3  15 Civilians Killed In Single US Airstrike Hav...   
4          4      4  Iranian woman jailed for fictional unpublished...   
...      ...    ...                                                ...   
18280  20795  20795  Rapper T.I.: Trump a ’Poster Child For White S...   
18281  20796  20796  N.F.L. Playoffs: Schedule, Matchups and Odds -...   
18282  20797  20797  Macy’s Is Said to Receive Takeover Approach by...   
18283  20798  20798  NATO, Russia To Hold Parallel Exercises In Bal...   
18284  20799  20799                          What Keeps the F-35 Alive   

                                          author  \
0                                  Darrell Lucus   
1                                Daniel J. Flynn   
2                             Consortiumnews.com   
3                                Jessica Purkiss   
4                                 Howard Portnoy   
...                                          ...   
18280                              Jerome Hudson   
18281                           Benjamin Hoffman   
18282  Michael J. de la Merced and Rachel Abrams   
18283                                Alex Ansary   
18284                              David Swanson   

                                                    text  
0      House Dem Aide: We Didn’t Even See Comey’s Let...  
1      Ever get the feeling your life circles the rou...  
2      Why the Truth Might Get You Fired October 29, ...  
3      Videos 15 Civilians Killed In Single US Airstr...  
4      Print \nAn Iranian woman has been sentenced to...  
...                                                  ...  
18280  Rapper T. I. unloaded on black celebrities who...  
18281  When the Green Bay Packers lost to the Washing...  
18282  The Macy’s of today grew from the union of sev...  
18283  NATO, Russia To Hold Parallel Exercises In Bal...  
18284    David Swanson is an author, activist, journa...  

[18285 rows x 5 columns]

In [275]:
import nltk
import re
from nltk.corpus import stopwords

In [276]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\gorui\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [277]:
len(content)

18285

In [278]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
corpus = []

for i in range(0, len(content)):
    review = re.sub('[^a-zA-Z]', ' ', content['title'][i])
    review = review.lower()
    review = review.split()
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

In [310]:
type(corpus)

list

In [311]:
corpus

['hous dem aid even see comey letter jason chaffetz tweet',
 'flynn hillari clinton big woman campu breitbart',
 'truth might get fire',
 'civilian kill singl us airstrik identifi',
 'iranian woman jail fiction unpublish stori woman stone death adulteri',
 'jacki mason hollywood would love trump bomb north korea lack tran bathroom exclus video breitbart',
 'beno hamon win french socialist parti presidenti nomin new york time',
 'back channel plan ukrain russia courtesi trump associ new york time',
 'obama organ action partner soro link indivis disrupt trump agenda',
 'bbc comedi sketch real housew isi caus outrag',
 'russian research discov secret nazi militari base treasur hunter arctic photo',
 'us offici see link trump russia',
 'ye paid govern troll social media blog forum websit',
 'major leagu soccer argentin find home success new york time',
 'well fargo chief abruptli step new york time',
 'anonym donor pay million releas everyon arrest dakota access pipelin',
 'fbi close hilla

In [280]:
onehot_repr = [one_hot(words, voc_size)for words in corpus]
onehot_repr

[[568, 3973, 7540, 8376, 8581, 5426, 3585, 9882, 650, 3074],
 [7858, 3341, 9281, 5871, 333, 992, 5455],
 [9250, 6539, 2426, 5202],
 [4286, 3989, 3146, 9771, 7129, 2009],
 [428, 333, 4221, 8895, 9977, 2772, 333, 6609, 8281, 8071],
 [4946,
  9705,
  845,
  3150,
  5700,
  2821,
  5279,
  1468,
  2402,
  6847,
  4035,
  7557,
  6889,
  7086,
  5455],
 [9290, 7909, 2190, 8028, 5961, 6263, 5536, 8038, 5910, 6769, 7327],
 [9046, 9653, 8282, 5449, 724, 4543, 2821, 4211, 5910, 6769, 7327],
 [22, 6245, 8975, 5067, 1613, 2935, 4354, 5513, 2821, 8105],
 [1219, 1028, 8415, 7075, 1013, 6743, 8505, 4232],
 [1544, 217, 3345, 8397, 8031, 8276, 5413, 6839, 8765, 5410, 4970],
 [9771, 9457, 8581, 2935, 2821, 724],
 [4570, 9010, 9602, 5476, 4996, 4608, 2113, 7540, 7324],
 [7249, 168, 8223, 436, 1114, 8636, 4235, 5910, 6769, 7327],
 [1552, 5284, 7929, 6998, 2182, 5910, 6769, 7327],
 [5167, 8670, 1166, 4021, 6507, 2607, 5869, 7632, 396, 1242],
 [3092, 5645, 3341],
 [427, 1326, 2833, 2267, 2821, 8083, 1759, 

In [281]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [282]:
# vectorizer = TfidfVectorizer()
# vectorizer.fit(corpus)
# X = vectorizer.transform(corpus)

In [283]:
corpus

['hous dem aid even see comey letter jason chaffetz tweet',
 'flynn hillari clinton big woman campu breitbart',
 'truth might get fire',
 'civilian kill singl us airstrik identifi',
 'iranian woman jail fiction unpublish stori woman stone death adulteri',
 'jacki mason hollywood would love trump bomb north korea lack tran bathroom exclus video breitbart',
 'beno hamon win french socialist parti presidenti nomin new york time',
 'back channel plan ukrain russia courtesi trump associ new york time',
 'obama organ action partner soro link indivis disrupt trump agenda',
 'bbc comedi sketch real housew isi caus outrag',
 'russian research discov secret nazi militari base treasur hunter arctic photo',
 'us offici see link trump russia',
 'ye paid govern troll social media blog forum websit',
 'major leagu soccer argentin find home success new york time',
 'well fargo chief abruptli step new york time',
 'anonym donor pay million releas everyon arrest dakota access pipelin',
 'fbi close hilla

In [284]:
sent_length=20
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
embedded_docs

array([[   0,    0,    0, ..., 9882,  650, 3074],
       [   0,    0,    0, ...,  333,  992, 5455],
       [   0,    0,    0, ..., 6539, 2426, 5202],
       ...,
       [   0,    0,    0, ..., 5910, 6769, 7327],
       [   0,    0,    0, ..., 6099, 7070, 8217],
       [   0,    0,    0, ..., 4421,  798, 5534]])

In [285]:

embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(LSTM(100))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

Model: "sequential_11"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_6 (Embedding)     (None, 20, 40)            400000    
                                                                 
 lstm_10 (LSTM)              (None, 100)               56400     
                                                                 
 dense_8 (Dense)             (None, 1)                 101       
                                                                 
Total params: 456,501
Trainable params: 456,501
Non-trainable params: 0
_________________________________________________________________
None


In [286]:
len(embedded_docs)

18285

In [287]:
y.shape

(18285,)

In [288]:
import numpy as np

In [289]:
X_final = np.array(embedded_docs)
y_final = np.array(y)

In [290]:
X_final.shape

(18285, 20)

In [291]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.33, random_state=42)

In [292]:
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)

Epoch 1/10
192/192 [==============================] - 9s 33ms/step - loss: 0.3303 - accuracy: 0.8433 - val_loss: 0.1857 - val_accuracy: 0.9218
Epoch 2/10
192/192 [==============================] - 8s 42ms/step - loss: 0.1267 - accuracy: 0.9511 - val_loss: 0.1889 - val_accuracy: 0.9218
Epoch 3/10
192/192 [==============================] - 8s 40ms/step - loss: 0.0765 - accuracy: 0.9735 - val_loss: 0.2238 - val_accuracy: 0.9228
Epoch 4/10
192/192 [==============================] - 9s 46ms/step - loss: 0.0510 - accuracy: 0.9840 - val_loss: 0.2416 - val_accuracy: 0.9198
Epoch 5/10
192/192 [==============================] - 8s 42ms/step - loss: 0.0334 - accuracy: 0.9898 - val_loss: 0.3230 - val_accuracy: 0.9175
Epoch 6/10
192/192 [==============================] - 7s 35ms/step - loss: 0.0216 - accuracy: 0.9938 - val_loss: 0.3359 - val_accuracy: 0.9150
Epoch 7/10
192/192 [==============================] - 6s 30ms/step - loss: 0.0163 - accuracy: 0.9947 - val_loss: 0.4168 - val_accuracy: 0.9087

In [293]:
y_pred=model.predict(X_train)


383/383 [==============================] - 2s 4ms/step


In [294]:
test = [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       2500, 8945, 6455, 9250, 9555, 1389, 5910, 6769, 7327]
test = np.array(test)

In [295]:
test

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       2500, 8945, 6455, 9250, 9555, 1389, 5910, 6769, 7327])

In [296]:
test.shape

(20,)

In [297]:
model.predict([[   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       2500, 8945, 6455, 9250, 9555, 1389, 5910, 6769, 7327]])

1/1 [==============================] - 0s 43ms/step


array([[3.032956e-06]], dtype=float32)

In [298]:
X_test[1]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       2500, 8945, 6455, 9250, 9555, 1389, 5910, 6769, 7327])

In [299]:
y_pred=(y_pred>0.5)
y_pred

array([[ True],
       [ True],
       [False],
       ...,
       [False],
       [False],
       [ True]])

In [300]:
y_pred[2]

array([False])

In [301]:
y_pred=y_pred.reshape(-1,)
y_pred

array([ True,  True, False, ..., False, False,  True])

In [302]:
from sklearn.metrics import confusion_matrix

In [303]:
# from tensorflow.keras.layers import Dropout
# ## Creating model
# embedding_vector_features=40
# model=Sequential()
# model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
# model.add(Dropout(0.3))
# model.add(LSTM(100))
# model.add(Dropout(0.3))
# model.add(Dense(1,activation='sigmoid'))
# model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [304]:
# model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)

In [305]:
# y_pred=model.predict(X_test)

In [306]:
# y_pred

In [307]:
def news_detector(content):

SyntaxError: incomplete input (2871036043.py, line 1)